var KEY='cicloela.v1';
var defaults={settings:{name:'',cycleLength:28,periodLength:5,lastPeriodStart:''},entries:{}};
var state=load(),view='today',cursor=new Date();
var moods=[['😞','Baixo'],['😕','Sensível'],['😐','Neutro'],['🙂','Bem'],['😄','Ótimo']];
var symptoms=['Cólica','Dor de cabeça','Inchaço','Sensibilidade mamária','Acne','Desejo por doces','Cansaço','Dor lombar','Náusea','Corrimento','Libido alta','Libido baixa'];
var flows=['Nenhum','Leve','Moderado','Intenso'];

function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{var x=JSON.parse(localStorage.getItem(KEY)||'{}');return {settings:Object.assign({},defaults.settings,x.settings||{}),entries:x.entries||{}}}catch(e){return clone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function iso(d){d=d||new Date();var x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)}
function date(s){return s?new Date(s+'T12:00:00'):null}
function add(d,n){var x=new Date(d);x.setDate(x.getDate()+n);return x}
function dd(a,b){return Math.round((a-b)/86400000)}
function fmt(s){var d=date(s);return d?d.toLocaleDateString('pt-BR',{day:'2-digit',month:'long',year:'numeric'}):'Não informado'}
function cap(s){return s?s.charAt(0).toUpperCase()+s.slice(1):s}
function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function entry(d){return state.entries[d]||{periodFlow:'Nenhum',mood:3,energy:3,pain:0,sleep:'',symptoms:[],notes:''}}
function cycle(target){var start=date(state.settings.lastPeriodStart),len=+state.settings.cycleLength||28,plen=+state.settings.periodLength||5;if(!start)return null;target=target||new Date();var delta=dd(target,start),i=Math.floor(delta/len),st=add(start,i*len),day=dd(target,st)+1,next=add(st,len),phase='Folicular';if(day<=plen)phase='Menstrual';else if(day>=Math.max(1,len-16)&&day<=Math.max(1,len-12))phase='Ovulatória estimada';else if(day>Math.max(1,len-12))phase='Lútea';return {day:day,len:len,plen:plen,next:next,until:dd(next,target),phase:phase}}
function toast(t){var x=document.createElement('div');x.textContent=t;x.style='position:fixed;left:50%;bottom:95px;transform:translateX(-50%);background:#302230;color:#fff;padding:10px 15px;border-radius:99px;z-index:50;font-weight:700';document.body.appendChild(x);setTimeout(function(){x.remove()},1600)}

function render(){var a=document.getElementById('app');if(view==='today')a.innerHTML=today();if(view==='calendar')a.innerHTML=calendar();if(view==='insights')a.innerHTML=insights();if(view==='settings')a.innerHTML=settings();bind()}
function today(){var d=iso(),e=entry(d),c=cycle(),welcome=state.settings.name?'Olá, '+esc(state.settings.name)+'.':'Seu dia, do seu jeito.';var flow=flows.map(function(f){return '<button class="flow '+(e.periodFlow===f?'selected':'')+'" data-flow="'+f+'">'+f+'</button>'}).join('');var mm=moods.map(function(m,i){return '<button class="mood '+(e.mood===i+1?'selected':'')+'" data-mood="'+(i+1)+'"><b>'+m[0]+'</b><small>'+m[1]+'</small></button>'}).join('');var ss=symptoms.map(function(s){return '<button class="chip '+((e.symptoms||[]).indexOf(s)>=0?'selected':'')+'" data-symptom="'+s+'">'+s+'</button>'}).join('');return '<section class="hero"><small>'+cap(new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'}))+'</small><h2>'+welcome+'</h2><p>'+(c?'Dia '+c.day+' do ciclo · fase '+c.phase.toLowerCase():'Configure o último ciclo para começar as estimativas.')+'</p></section><section class="grid"><div class="stat"><small>Próxima menstruação</small><br><strong>'+(c?(c.until===0?'Hoje':c.until>0?c.until+' dias':'Recalcular'):'—')+'</strong></div><div class="stat"><small>Humor de hoje</small><br><strong>'+moods[(e.mood||3)-1][0]+'</strong></div></section><section class="card"><h2>Registro de hoje</h2><p class="muted">'+fmt(d)+'</p><div class="field"><label>Fluxo menstrual</label><div class="row">'+flow+'</div></div><div class="field"><label>Humor</label><div class="moods">'+mm+'</div></div><div class="field"><label>Energia: <span id="ev">'+(e.energy||3)+'/5</span></label><input id="energy" type="range" min="1" max="5" value="'+(e.energy||3)+'"></div><div class="field"><label>Dor/cólica: <span id="pv">'+(e.pain||0)+'/10</span></label><input id="pain" type="range" min="0" max="10" value="'+(e.pain||0)+'"></div><div class="field"><label>Sono (horas)</label><input id="sleep" type="number" min="0" max="24" step="0.5" value="'+(e.sleep||'')+'" placeholder="Ex.: 7.5"></div><div class="field"><label>Sintomas e sinais</label><div class="chips">'+ss+'</div></div><div class="field"><label>Anotações</label><textarea id="notes" placeholder="Como você se sentiu?">'+esc(e.notes)+'</textarea></div><button id="saveToday" class="primary">Salvar registro</button><div class="notice">As estimativas são informativas. Não use o app como método contraceptivo ou para diagnóstico.</div></section>'}
function calendar(){var y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),off=(first.getDay()+6)%7,cells='',i;for(i=0;i<off;i++)cells+='<div></div>';for(i=1;i<=last.getDate();i++){var dt=new Date(y,m,i),s=iso(dt),e=state.entries[s],c=cycle(dt),rp=e&&e.periodFlow&&e.periodFlow!=='Nenhum',pr=c&&c.day<=c.plen&&!rp;cells+='<button class="day '+(s===iso()?'today ':'')+(rp?'period ':'')+(pr?'pred ':'')+(e?'mark':'')+'" data-day="'+s+'">'+i+'</button>'}return '<section class="card"><div class="calhead"><button id="prev">‹</button><h2>'+cap(first.toLocaleDateString('pt-BR',{month:'long',year:'numeric'}))+'</h2><button id="next">›</button></div><div class="calendar">'+['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(function(x){return '<div class="dow">'+x+'</div>'}).join('')+cells+'</div><div class="legend">Rosa: menstruação registrada · tracejado: previsão · ponto roxo: dia com registro.</div></section><section class="card"><h3>Como ler</h3><p class="muted">A previsão usa a duração média configurada. Ciclos podem variar naturalmente.</p></section>'}
function insights(){var arr=Object.entries(state.entries).filter(function(x){return dd(new Date(),date(x[0]))<=30});if(!arr.length)return '<section class="card"><h2>Insights</h2><p class="muted">Registre alguns dias para começar a visualizar padrões.</p></section>';function avg(k){var v=arr.map(function(x){return +x[1][k]}).filter(Number.isFinite);return v.length?(v.reduce(function(a,b){return a+b},0)/v.length).toFixed(1):'—'}var counts={};arr.forEach(function(x){(x[1].symptoms||[]).forEach(function(s){counts[s]=(counts[s]||0)+1})});var top=Object.entries(counts).sort(function(a,b){return b[1]-a[1]}).slice(0,3).map(function(x){return x[0]+' ('+x[1]+'×)'}).join(' · ')||'Sem dados suficientes';return '<section class="grid three"><div class="stat"><small>Humor médio</small><br><strong>'+avg('mood')+'/5</strong></div><div class="stat"><small>Energia média</small><br><strong>'+avg('energy')+'/5</strong></div><div class="stat"><small>Dor média</small><br><strong>'+avg('pain')+'/10</strong></div></section><section class="card"><h2>Últimos 30 dias</h2><div class="insight"><strong>🌙 Sono</strong><p class="muted">Média: '+avg('sleep')+' h/noite.</p></div><div class="insight"><strong>🌸 Sinais mais frequentes</strong><p class="muted">'+top+'</p></div><div class="insight"><strong>🧭 Diário de padrões</strong><p class="muted">Use os registros para conversar com um profissional de saúde se notar sintomas persistentes ou mudanças importantes.</p></div></section>'}
function settings(){var s=state.settings;return '<section class="card"><h2>Ajustes do ciclo</h2><div class="field"><label>Nome (opcional)</label><input id="name" value="'+esc(s.name)+'"></div><div class="field"><label>Primeiro dia da última menstruação</label><input id="last" type="date" value="'+(s.lastPeriodStart||'')+'"></div><div class="field"><label>Duração média do ciclo</label><input id="cl" type="number" min="15" max="60" value="'+s.cycleLength+'"></div><div class="field"><label>Duração média da menstruação</label><input id="pl" type="number" min="1" max="15" value="'+s.periodLength+'"></div><button id="saveSettings" class="primary">Salvar ajustes</button></section><section class="card"><h2>Seus dados</h2><div class="setting"><strong>Exportar backup</strong><p class="muted">Baixe um JSON com seus registros.</p><button id="export" class="secondary">Exportar JSON</button></div><div class="setting"><strong>Importar backup</strong><p class="muted">Restaure um backup do CicloEla.</p><input id="import" type="file" accept="application/json"></div><div class="setting"><strong>Apagar tudo</strong><p class="muted">Remove os dados deste navegador.</p><button id="clear" class="danger">Apagar dados locais</button></div></section><section class="card"><h2>Sobre</h2><p class="muted">CicloEla MVP · dados locais · sem conta · sem anúncios · sem rastreamento.</p></section>'}

function bind(){if(view==='today'){var draft=clone(entry(iso()));document.querySelectorAll('[data-flow]').forEach(function(b){b.onclick=function(){draft.periodFlow=b.dataset.flow;document.querySelectorAll('[data-flow]').forEach(function(x){x.classList.toggle('selected',x===b)})}});document.querySelectorAll('[data-mood]').forEach(function(b){b.onclick=function(){draft.mood=+b.dataset.mood;document.querySelectorAll('[data-mood]').forEach(function(x){x.classList.toggle('selected',x===b)})}});document.querySelectorAll('[data-symptom]').forEach(function(b){b.onclick=function(){var s=b.dataset.symptom,d=draft.symptoms||[];draft.symptoms=d.indexOf(s)>=0?d.filter(function(x){return x!==s}):d.concat([s]);b.classList.toggle('selected')}});energy.oninput=function(){draft.energy=+energy.value;ev.textContent=energy.value+'/5'};pain.oninput=function(){draft.pain=+pain.value;pv.textContent=pain.value+'/10'};saveToday.onclick=function(){draft.sleep=sleep.value;draft.notes=notes.value.trim();state.entries[iso()]=draft;if(draft.periodFlow!=='Nenhum'&&!state.settings.lastPeriodStart)state.settings.lastPeriodStart=iso();save();toast('Registro salvo ✓');render()}}if(view==='calendar'){prev.onclick=function(){cursor=new Date(cursor.getFullYear(),cursor.getMonth()-1,1);render()};next.onclick=function(){cursor=new Date(cursor.getFullYear(),cursor.getMonth()+1,1);render()};document.querySelectorAll('[data-day]').forEach(function(b){b.onclick=function(){var d=b.dataset.day,e=state.entries[d];alert(e?fmt(d)+'\nFluxo: '+e.periodFlow+'\nHumor: '+moods[(e.mood||3)-1][1]+'\nEnergia: '+(e.energy||'—')+'/5\nDor: '+(e.pain||0)+'/10\nSono: '+(e.sleep||'—')+' h\nSintomas: '+((e.symptoms||[]).join(', ')||'Nenhum')+'\n\n'+(e.notes||''):fmt(d)+'\nSem registro.')}})}if(view==='settings'){saveSettings.onclick=function(){state.settings={name:name.value.trim(),lastPeriodStart:last.value,cycleLength:+cl.value||28,periodLength:+pl.value||5};save();toast('Ajustes salvos ✓');render()};document.getElementById('export').onclick=function(){var blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cicloela-backup-'+iso()+'.json';a.click();URL.revokeObjectURL(a.href)};document.getElementById('import').onchange=async function(ev){var f=ev.target.files[0];if(!f)return;try{var p=JSON.parse(await f.text());if(!p.settings||!p.entries)throw 0;state=p;save();toast('Backup importado ✓');render()}catch(e){alert('Backup inválido.')}};clear.onclick=function(){if(confirm('Apagar todos os dados deste navegador?')){state=clone(defaults);save();render();toast('Dados apagados')}}}}
document.querySelectorAll('nav button').forEach(function(b){b.onclick=function(){view=b.dataset.view;document.querySelectorAll('nav button').forEach(function(x){x.classList.toggle('active',x===b)});render()}});
privacy.onclick=function(){privacyDialog.showModal()};closePrivacy.onclick=function(){privacyDialog.close()};
if('serviceWorker' in navigator)window.addEventListener('load',function(){navigator.serviceWorker.register('./sw.js').catch(function(){})});
render();